dist: xenial
language: php

php:
  - 7.3
  - 7.4
  - 8.0

jobs:
  include:
    - php: 7.3
      env: LARAVEL_VERSION=7.*
    - php: 7.3
      env: LARAVEL_VERSION=8.*
    - php: 7.4
      env: LARAVEL_VERSION=7.*
    - php: 7.4
      env: LARAVEL_VERSION=8.*
    - php: 8.0
      env: LARAVEL_VERSION=8.*

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${LARAVEL_VERSION}" --no-update
  - travis_retry composer update --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
